##### MYSQL #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql-db
  template:
    metadata:
      name: my-mysql-pod
      labels:
        app: my-mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:latest # mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume
          env:
            - name: MYSQL_SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-pvc

---

##### MONGO #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mongo-db
  template:
    metadata:
      labels:
        app: my-mongo-db
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: mongo-db
          image: mongo # mongo
          imagePullPolicy: IfNotPresent
          args: [ "mongod", "--config", "/etc/mongod.conf"]
          env:
            - name: MONGO_SECRET_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
            - name: mongo-config-volume
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-config-volume
          configMap:
            name: mongo-config