##### MYSQL #####
apiVersion: v1
kind: Service
metadata:
  name: my-mysql-service
  labels:
    app: my-mysql-db-service
spec:
  type: LoadBalancer
  ports:
    - port: 13006
      targetPort: 3306
  selector:
    app: my-mysql-db