apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      name: my-server-pod
      labels:
        app: my-server
    spec:
      containers:
        - name: spring-server
          image: contest73-backend.kr.ncr.ntruss.com/contest73-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "default-my-mysql-service-790b6-26292068-46a4f0920895.kr.lb.naverncp.com"
            - name: MYSQL_PORT
              value: "13006"
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: NCP_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: ncp-access-key
            - name: NCP_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: ncp-secret-key
      imagePullSecrets:
        - name: regcred