apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: my-server-pod
      labels:
        app: my-server
    spec:
      containers:
        - name: spring-server
          image: contest73-backend.kr.ncr.ntruss.com/contest73-backend:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred