spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/bklocal

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/bkmongo

  batch:
    jdbc:
      initialize-schema: always

ncp:
  accessKey: ${NCP_ACCESSKEY}
  secretKey: ${NCP_SECRETKEY}
